"""empty message

Revision ID: 0f66ace7b23c
Revises: None
Create Date: 2016-09-22 10:26:52.350154

"""

# revision identifiers, used by Alembic.
revision = '0f66ace7b23c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eggs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spams')
    op.drop_table('eggs')
    ### end Alembic commands ###
